---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.jenkins.deployment_name }}-casc-cm
  namespace: {{ $.Release.Namespace }}
data:
  {{ tpl (.Files.Glob "conf/**").AsConfig . | nindent 2 }}

