---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.jenkins.deployment_name }}-service
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
{{- range .Values.services }}
  - port: {{ .port }}
    name: {{ .name }}
    protocol: {{ .protocol }}
    targetPort: {{ .port }}
{{- end }}
  selector:
    app: {{ .Values.jenkins.app_selector }}
  sessionAffinity: None
  type: ClusterIP

